version: '3.8'

services:
  # Main application
  physiotherapy-scheduler:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=jdbc:sqlite:/app/data/scheduler.db
      - HTTP_PORT=3000
      - LOG_LEVEL=info
    volumes:
      - scheduler_data:/app/data
      - scheduler_logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.scheduler.rule=Host(`scheduler.local`)"
      - "traefik.http.services.scheduler.loadbalancer.server.port=3000"

  # Reverse proxy (optional)
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  # Database backup service
  db-backup:
    image: alpine:3.18
    volumes:
      - scheduler_data:/data
      - scheduler_backups:/backups
    environment:
      - BACKUP_SCHEDULE=0 2 * * *  # Daily at 2 AM
    command: >
      sh -c "
        apk add --no-cache sqlite dcron &&
        echo '0 2 * * * cp /data/scheduler.db /backups/scheduler_$(date +%Y%m%d_%H%M%S).db && find /backups -name \"scheduler_*.db\" -mtime +7 -delete' | crontab - &&
        crond -f
      "
    restart: unless-stopped

volumes:
  scheduler_data:
    driver: local
  scheduler_logs:
    driver: local
  scheduler_backups:
    driver: local

networks:
  default:
    driver: bridge
